import { Blueprint } from '@/utils/grid';

export const blueprints: Blueprint[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    icon: '📸',
    description: 'Photo grid 3 columns with story bar',
    config: {
      columns: 3,
      rows: 4,
      gap: 2,
      columnSizes: ['1fr', '1fr', '1fr'],
      rowSizes: ['60px', '1fr', '1fr', '1fr'],
      justifyItems: 'stretch',
      alignItems: 'stretch',
      layoutType: 'grid',
      cells: [
        { id: 'stories', label: 'Stories Bar', rowStart: 1, rowEnd: 2, colStart: 1, colEnd: 4, color: '35 100% 60%' },
        { id: 'post1', label: 'Post', rowStart: 2, rowEnd: 3, colStart: 1, colEnd: 2, color: '187 100% 50%' },
        { id: 'post2', label: 'Post', rowStart: 2, rowEnd: 3, colStart: 2, colEnd: 3, color: '187 80% 45%' },
        { id: 'post3', label: 'Post', rowStart: 2, rowEnd: 3, colStart: 3, colEnd: 4, color: '187 60% 40%' },
        { id: 'post4', label: 'Post', rowStart: 3, rowEnd: 4, colStart: 1, colEnd: 2, color: '280 80% 60%' },
        { id: 'post5', label: 'Post', rowStart: 3, rowEnd: 4, colStart: 2, colEnd: 3, color: '280 60% 55%' },
        { id: 'post6', label: 'Post', rowStart: 3, rowEnd: 4, colStart: 3, colEnd: 4, color: '280 40% 50%' },
        { id: 'post7', label: 'Reel', rowStart: 4, rowEnd: 5, colStart: 1, colEnd: 2, color: '140 70% 50%' },
        { id: 'post8', label: 'Reel', rowStart: 4, rowEnd: 5, colStart: 2, colEnd: 4, color: '140 50% 45%' },
      ],
    },
  },
  {
    id: 'netflix',
    name: 'Netflix',
    icon: '🎬',
    description: 'Hero + rows of content',
    config: {
      columns: 4,
      rows: 4,
      gap: 3,
      columnSizes: ['1fr', '1fr', '1fr', '1fr'],
      rowSizes: ['200px', '120px', '120px', '120px'],
      justifyItems: 'stretch',
      alignItems: 'stretch',
      layoutType: 'grid',
      cells: [
        { id: 'hero', label: 'Hero Banner', rowStart: 1, rowEnd: 2, colStart: 1, colEnd: 5, color: '350 80% 60%' },
        { id: 'trend1', label: 'Trending', rowStart: 2, rowEnd: 3, colStart: 1, colEnd: 2, color: '187 100% 50%' },
        { id: 'trend2', label: 'Trending', rowStart: 2, rowEnd: 3, colStart: 2, colEnd: 3, color: '187 80% 45%' },
        { id: 'trend3', label: 'Trending', rowStart: 2, rowEnd: 3, colStart: 3, colEnd: 4, color: '187 60% 40%' },
        { id: 'trend4', label: 'Trending', rowStart: 2, rowEnd: 3, colStart: 4, colEnd: 5, color: '187 40% 35%' },
        { id: 'new1', label: 'New', rowStart: 3, rowEnd: 4, colStart: 1, colEnd: 2, color: '35 100% 60%' },
        { id: 'new2', label: 'New', rowStart: 3, rowEnd: 4, colStart: 2, colEnd: 3, color: '35 80% 55%' },
        { id: 'new3', label: 'New', rowStart: 3, rowEnd: 4, colStart: 3, colEnd: 4, color: '35 60% 50%' },
        { id: 'new4', label: 'New', rowStart: 3, rowEnd: 4, colStart: 4, colEnd: 5, color: '35 40% 45%' },
        { id: 'top1', label: 'Top 10', rowStart: 4, rowEnd: 5, colStart: 1, colEnd: 3, color: '280 80% 60%' },
        { id: 'top2', label: 'Top 10', rowStart: 4, rowEnd: 5, colStart: 3, colEnd: 5, color: '280 60% 55%' },
      ],
    },
  },
  {
    id: 'airbnb',
    name: 'Airbnb',
    icon: '🏠',
    description: 'Grid of cards with filter sidebar',
    config: {
      columns: 4,
      rows: 4,
      gap: 4,
      columnSizes: ['250px', '1fr', '1fr', '1fr'],
      rowSizes: ['60px', '1fr', '1fr', '1fr'],
      justifyItems: 'stretch',
      alignItems: 'stretch',
      layoutType: 'grid',
      cells: [
        { id: 'search', label: 'Search Bar', rowStart: 1, rowEnd: 2, colStart: 1, colEnd: 5, color: '350 80% 60%' },
        { id: 'filters', label: 'Filters', rowStart: 2, rowEnd: 5, colStart: 1, colEnd: 2, color: '220 30% 20%' },
        { id: 'card1', label: 'Listing', rowStart: 2, rowEnd: 3, colStart: 2, colEnd: 3, color: '187 100% 50%' },
        { id: 'card2', label: 'Listing', rowStart: 2, rowEnd: 3, colStart: 3, colEnd: 4, color: '187 80% 45%' },
        { id: 'card3', label: 'Listing', rowStart: 2, rowEnd: 3, colStart: 4, colEnd: 5, color: '140 70% 50%' },
        { id: 'card4', label: 'Listing', rowStart: 3, rowEnd: 4, colStart: 2, colEnd: 3, color: '35 100% 60%' },
        { id: 'card5', label: 'Listing', rowStart: 3, rowEnd: 4, colStart: 3, colEnd: 4, color: '35 80% 55%' },
        { id: 'card6', label: 'Listing', rowStart: 3, rowEnd: 4, colStart: 4, colEnd: 5, color: '280 80% 60%' },
        { id: 'map', label: 'Map View', rowStart: 4, rowEnd: 5, colStart: 2, colEnd: 5, color: '200 90% 55%' },
      ],
    },
  },
];
